name: Test
on:
  [ pull_request, push ]

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -warnAsError ZipishLens
      - name: Inspection
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: ./ZipishLens.sln
          exclude: ZipishLens/wwwroot/**
          minimumReportSeverity: 'WARNING'
  deploy:
    needs: [ code_analysis ]
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Build
        run: |
          dotnet publish -c Release ZippishLens -o output
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy output/wwwroot --project-name=zipish-lens
