name: Test
on:
  [ pull_request, push ]

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -warnAsError ZipishLens
      - name: Inspection
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: ./ZipishLens.sln
          exclude: ZipishLens/wwwroot/**
